// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Gimmer_Core","status":true,"description":"v1.5 - General plugin framework for my other plugins","parameters":{"---Parameters---":"","debug":"false","Advanced Debug":"false","Show Mouse Coordinates":"false","---Helpers---":"","Block F5 Reload":"false"}},
{"name":"Gimmer_SpottingPlayers","status":true,"description":"v1.1 - A plugin to allow NPC events to \"spot the player\" and send execute a common event","parameters":{"---Parameters---":"","Common Event":"1","Map ID Variable":"1","Starting X Variable":"2","Starting Y Variable":"3","Solid Wall Region Id":"1","Track Spotter For Balloons":"true","Track Map Position":"true"}},
{"name":"fullscreen","status":true,"description":"v1.1 Add fullscreen option, force fullscreen in Stretch Mode and disable F3.","parameters":{"fullscreenOptionName":"Fullscreen","forceFullscreen":"false","Add command to option?":"false","Disable F3?":"true","Disable F4?":"false"}}
];
